// AUTO-GENERATED by scripts/sync-template-overlays.ts — DO NOT EDIT BY HAND.
// Source of truth: data/companies/*.md
//
// Re-runs at the end of every `tsx scripts/seed-profiles.ts` invocation.
// Wired into lib/profiles/template/data/index.ts as the last overlay layer
// so anything added to a profile MD shows up on /app/companies/<slug>.

import type { CompanyTemplateData } from "../schema";

export const autoMdSync: Record<string, Partial<CompanyTemplateData>> = {
  "ab-inbev": {
    leadership: {
      presenter: {
        html: "<strong>David Almeida</strong> — Chief Strategy &amp; Technology Officer.",
        source: { label: "📄 Announcement", url: "https://www.ab-inbev.com/our-leaders-david-almeida" },
      },
    },
    production: {
      namedTools: {
        tools: [
        { html: "<strong>Pluto7 / K Filter optimisation (Google Cloud)</strong> <span style=\"color:var(--text-mid)\">ops</span>", source: { label: "📄 Source", url: "https://cloud.google.com/customers/abinbev-pluto7" } },
        { html: "<strong>BEES platform</strong> <span style=\"color:var(--text-mid)\">supply_chain</span>", source: { label: "📄 Source", url: "https://consumergoods.com/why-ab-inbevs-supply-chain-overhaul-focused-touchless-planning" } },
        { html: "<strong>CatExpert.ai</strong> <span style=\"color:var(--text-mid)\">merchandising</span>", source: { label: "📄 Source", url: "https://manufacturingleadershipcouncil.com/ab-inbev-uses-smart-manufacturing-for-award-winning-results-32530/" } },
        { html: "<strong>Bevi chatbot (Avaamo / WhatsApp)</strong> <span style=\"color:var(--text-mid)\">consumer</span>", source: { label: "📄 Source", url: "https://manufacturingleadershipcouncil.com/ab-inbev-uses-smart-manufacturing-for-award-winning-results-32530/" } },
        { html: "<strong>DeepHow</strong> <span style=\"color:var(--text-mid)\">ops</span>", source: { label: "📄 Source", url: "https://manufacturingleadershipcouncil.com/ab-inbev-uses-smart-manufacturing-for-award-winning-results-32530/" } },
        { html: "<strong>AnswerRocket</strong> <span style=\"color:var(--text-mid)\">analytics</span>", source: { label: "📄 Source", url: "https://www.boardofinnovation.com/blog/the-role-of-generative-ai-in-your-innovation-process/" } },
        { html: "<strong>Smart Barley</strong> <span style=\"color:var(--text-mid)\">supply_chain</span>", source: { label: "📄 Source", url: "https://manufacturingleadershipcouncil.com/ab-inbev-uses-smart-manufacturing-for-award-winning-results-32530/" } },
        { html: "<strong>Azure Synapse Analytics + Power BI</strong> <span style=\"color:var(--text-mid)\">analytics</span>", source: { label: "📄 Source", url: "https://www.microsoft.com/en/customers/story/1513234381485102673-abinbev-professionalservices" } },
        ],
        sources: [
        { label: "📄 Pluto7 / K Filter optimisation (Google Cloud)", url: "https://cloud.google.com/customers/abinbev-pluto7" },
        { label: "📄 BEES platform", url: "https://consumergoods.com/why-ab-inbevs-supply-chain-overhaul-focused-touchless-planning" },
        { label: "📄 CatExpert.ai", url: "https://manufacturingleadershipcouncil.com/ab-inbev-uses-smart-manufacturing-for-award-winning-results-32530/" },
        { label: "📄 Bevi chatbot (Avaamo / WhatsApp)", url: "https://manufacturingleadershipcouncil.com/ab-inbev-uses-smart-manufacturing-for-award-winning-results-32530/" },
        { label: "📄 DeepHow", url: "https://manufacturingleadershipcouncil.com/ab-inbev-uses-smart-manufacturing-for-award-winning-results-32530/" },
        { label: "📄 AnswerRocket", url: "https://www.boardofinnovation.com/blog/the-role-of-generative-ai-in-your-innovation-process/" },
        { label: "📄 Smart Barley", url: "https://manufacturingleadershipcouncil.com/ab-inbev-uses-smart-manufacturing-for-award-winning-results-32530/" },
        { label: "📄 Azure Synapse Analytics + Power BI", url: "https://www.microsoft.com/en/customers/story/1513234381485102673-abinbev-professionalservices" },
        ],
      },
    },
    sources: [
      { label: "📄 Pluto7 / K Filter optimisation (Google Cloud)", url: "https://cloud.google.com/customers/abinbev-pluto7" },
      { label: "📄 BEES platform", url: "https://consumergoods.com/why-ab-inbevs-supply-chain-overhaul-focused-touchless-planning" },
      { label: "📄 CatExpert.ai", url: "https://manufacturingleadershipcouncil.com/ab-inbev-uses-smart-manufacturing-for-award-winning-results-32530/" },
      { label: "📄 AnswerRocket", url: "https://www.boardofinnovation.com/blog/the-role-of-generative-ai-in-your-innovation-process/" },
      { label: "📄 Azure Synapse Analytics + Power BI", url: "https://www.microsoft.com/en/customers/story/1513234381485102673-abinbev-professionalservices" },
      { label: "📄 David Almeida — leadership announcement", url: "https://www.ab-inbev.com/our-leaders-david-almeida" },
    ],
  },
  "ahold-delhaize": {
    leadership: {
      presenter: {
        html: "<strong>Jan Brecht</strong> — Chief Technology Officer (ExCom, since 26 Sept 2025).",
        source: { label: "📄 Announcement", url: "https://newsroom.aholddelhaize.com/ahold-delhaize-appoints-jan-brecht-as-chief-technology-officer-and-member-of-the-executive-committee-succeeding-ben-wishart/" },
      },
    },
    production: {
      namedTools: {
        tools: [
        { html: "<strong>My AH Assistant + Steijn chatbot</strong> <span style=\"color:var(--text-mid)\">consumer</span>", source: { label: "📄 Source", url: "https://www.microsoft.com/en/customers/story/1739352737304784739-albertheijn-azure-open-ai-service-retailers-en-netherlands" } },
        { html: "<strong>Scan &amp; Kook</strong> <span style=\"color:var(--text-mid)\">consumer</span>", source: { label: "📄 Source", url: "https://www.esmmagazine.com/technology/albert-heijn-adds-new-gen-ai-based-feature-scan-kook-to-its-app-267573" } },
        { html: "<strong>Bol Spot &amp; Shop</strong> <span style=\"color:var(--text-mid)\">consumer</span>", source: { label: "📄 Source", url: "https://newsroom.aholddelhaize.com/ahold-delhaize-reports-strong-q4-2025-financial-results-priorities-and-outlook-for-2026-underpin-our-value-creation-and-progress-towards-our-growing-together-ambitions/" } },
        { html: "<strong>Marty robots</strong> <span style=\"color:var(--text-mid)\">ops</span>", source: { label: "📄 Source", url: "https://thecounter.org/supermarket-robot-automation-ai-organized-labor-stop-and-shop/" } },
        { html: "<strong>Flybuy AI</strong> <span style=\"color:var(--text-mid)\">ops</span>", source: { label: "📄 Source", url: "https://www.ecommercenorthamerica.org/2025/07/10/food-lion-ai-curbside-pickup/" } },
        { html: "<strong>Albert Heijn bakery AI (dynamic pricing + waste prediction)</strong> <span style=\"color:var(--text-mid)\">ops</span>", source: { label: "📄 Source", url: "https://www.retaildetail.eu/news/food/albert-heijn-reduces-bakery-waste-using-ai/" } },
        { html: "<strong>AH employee AI assistant (Azure OpenAI)</strong> <span style=\"color:var(--text-mid)\">ops</span>", source: { label: "📄 Source", url: "https://www.microsoft.com/en/customers/story/24372-koninklijke-ahold-delhaize-azure-openai" } },
        { html: "<strong>Harmonya + Protex AI (via W23 Global venture fund)</strong> <span style=\"color:var(--text-mid)\">ops</span>", source: { label: "📄 Source", url: "https://newsroom.aholddelhaize.com/ahold-delhaize-invests-in-ai-powered-start-ups-through-w23-global-to-advance-customer-focused-innovation/" } },
        ],
        sources: [
        { label: "📄 My AH Assistant + Steijn chatbot", url: "https://www.microsoft.com/en/customers/story/1739352737304784739-albertheijn-azure-open-ai-service-retailers-en-netherlands" },
        { label: "📄 Scan & Kook", url: "https://www.esmmagazine.com/technology/albert-heijn-adds-new-gen-ai-based-feature-scan-kook-to-its-app-267573" },
        { label: "📄 Bol Spot & Shop", url: "https://newsroom.aholddelhaize.com/ahold-delhaize-reports-strong-q4-2025-financial-results-priorities-and-outlook-for-2026-underpin-our-value-creation-and-progress-towards-our-growing-together-ambitions/" },
        { label: "📄 Marty robots", url: "https://thecounter.org/supermarket-robot-automation-ai-organized-labor-stop-and-shop/" },
        { label: "📄 Flybuy AI", url: "https://www.ecommercenorthamerica.org/2025/07/10/food-lion-ai-curbside-pickup/" },
        { label: "📄 Albert Heijn bakery AI (dynamic pricing + waste prediction)", url: "https://www.retaildetail.eu/news/food/albert-heijn-reduces-bakery-waste-using-ai/" },
        { label: "📄 AH employee AI assistant (Azure OpenAI)", url: "https://www.microsoft.com/en/customers/story/24372-koninklijke-ahold-delhaize-azure-openai" },
        { label: "📄 Harmonya + Protex AI (via W23 Global venture fund)", url: "https://newsroom.aholddelhaize.com/ahold-delhaize-invests-in-ai-powered-start-ups-through-w23-global-to-advance-customer-focused-innovation/" },
        ],
      },
    },
    sources: [
      { label: "📄 My AH Assistant + Steijn chatbot", url: "https://www.microsoft.com/en/customers/story/1739352737304784739-albertheijn-azure-open-ai-service-retailers-en-netherlands" },
      { label: "📄 Scan & Kook", url: "https://www.esmmagazine.com/technology/albert-heijn-adds-new-gen-ai-based-feature-scan-kook-to-its-app-267573" },
      { label: "📄 Bol Spot & Shop", url: "https://newsroom.aholddelhaize.com/ahold-delhaize-reports-strong-q4-2025-financial-results-priorities-and-outlook-for-2026-underpin-our-value-creation-and-progress-towards-our-growing-together-ambitions/" },
      { label: "📄 Marty robots", url: "https://thecounter.org/supermarket-robot-automation-ai-organized-labor-stop-and-shop/" },
      { label: "📄 Flybuy AI", url: "https://www.ecommercenorthamerica.org/2025/07/10/food-lion-ai-curbside-pickup/" },
      { label: "📄 Albert Heijn bakery AI (dynamic pricing + waste prediction)", url: "https://www.retaildetail.eu/news/food/albert-heijn-reduces-bakery-waste-using-ai/" },
      { label: "📄 AH employee AI assistant (Azure OpenAI)", url: "https://www.microsoft.com/en/customers/story/24372-koninklijke-ahold-delhaize-azure-openai" },
      { label: "📄 Harmonya + Protex AI (via W23 Global venture fund)", url: "https://newsroom.aholddelhaize.com/ahold-delhaize-invests-in-ai-powered-start-ups-through-w23-global-to-advance-customer-focused-innovation/" },
      { label: "📄 Jan Brecht — leadership announcement", url: "https://newsroom.aholddelhaize.com/ahold-delhaize-appoints-jan-brecht-as-chief-technology-officer-and-member-of-the-executive-committee-succeeding-ben-wishart/" },
    ],
  },
  "arla": {
    leadership: {
      presenter: {
        html: "<strong>Mia Heslegrave</strong> — Chief Information Officer (since 1 Feb 2025).",
        source: { label: "📄 Announcement", url: "https://www.arla.com/company/news-and-press/2025/pressrelease/leadership-change-in-arlas-it-organisation/" },
      },
    },
    production: {
      namedTools: {
        tools: [
        { html: "<strong>Milk-yield prediction AI</strong> <span style=\"color:var(--text-mid)\">supply_chain</span>", source: { label: "📄 Source", url: "https://www.fooddive.com/news/arla-foods-uses-ai-to-steer-milk-projections/556773/" } },
        { html: "<strong>Azure OpenAI for recipes</strong> <span style=\"color:var(--text-mid)\">consumer</span>", source: { label: "📄 Source", url: "https://www.microsoft.com/en/customers/story/21768-arla-foods-azure-open-ai-service" } },
        { html: "<strong>Centralised data foundation (Azure + Power BI)</strong> <span style=\"color:var(--text-mid)\">analytics</span>", source: { label: "📄 Source", url: "https://www.microsoft.com/en/customers/story/827449-arla-foods-consumer-goods-power-bi" } },
        { html: "<strong>GEO pilot (Azoma + CARAT)</strong> <span style=\"color:var(--text-mid)\">marketing</span>", source: { label: "📄 Source", url: "https://www.thegrocer.co.uk/news/arla-and-mars-pilot-geo-platform-to-boost-brand-visibility-on-ai-answer-engines/709430.article" } },
        ],
        sources: [
        { label: "📄 Milk-yield prediction AI", url: "https://www.fooddive.com/news/arla-foods-uses-ai-to-steer-milk-projections/556773/" },
        { label: "📄 Azure OpenAI for recipes", url: "https://www.microsoft.com/en/customers/story/21768-arla-foods-azure-open-ai-service" },
        { label: "📄 Centralised data foundation (Azure + Power BI)", url: "https://www.microsoft.com/en/customers/story/827449-arla-foods-consumer-goods-power-bi" },
        { label: "📄 GEO pilot (Azoma + CARAT)", url: "https://www.thegrocer.co.uk/news/arla-and-mars-pilot-geo-platform-to-boost-brand-visibility-on-ai-answer-engines/709430.article" },
        ],
      },
    },
    sources: [
      { label: "📄 Milk-yield prediction AI", url: "https://www.fooddive.com/news/arla-foods-uses-ai-to-steer-milk-projections/556773/" },
      { label: "📄 Azure OpenAI for recipes", url: "https://www.microsoft.com/en/customers/story/21768-arla-foods-azure-open-ai-service" },
      { label: "📄 Centralised data foundation (Azure + Power BI)", url: "https://www.microsoft.com/en/customers/story/827449-arla-foods-consumer-goods-power-bi" },
      { label: "📄 GEO pilot (Azoma + CARAT)", url: "https://www.thegrocer.co.uk/news/arla-and-mars-pilot-geo-platform-to-boost-brand-visibility-on-ai-answer-engines/709430.article" },
      { label: "📄 Mia Heslegrave — leadership announcement", url: "https://www.arla.com/company/news-and-press/2025/pressrelease/leadership-change-in-arlas-it-organisation/" },
    ],
  },
  "asos": {
    leadership: {
      presenter: {
        html: "<strong>Papinder Dosanjh</strong> — Director of AI and Machine Learning.",
        source: { label: "📄 Announcement", url: "https://ukstories.microsoft.com/features/asos-and-microsoft-announce-new-three-year-ai-collaboration/" },
      },
    },
    production: {
      namedTools: {
        tools: [
        { html: "<strong>AI Stylist</strong> <span style=\"color:var(--text-mid)\">consumer</span>", source: { label: "📄 Source", url: "https://ukstories.microsoft.com/features/asos-and-microsoft-announce-new-three-year-ai-collaboration/" } },
        { html: "<strong>GitHub Copilot</strong> <span style=\"color:var(--text-mid)\">ops</span>", source: { label: "📄 Source", url: "https://ukstories.microsoft.com/features/asos-and-microsoft-announce-new-three-year-ai-collaboration/" } },
        { html: "<strong>Microsoft 365 Copilot</strong> <span style=\"color:var(--text-mid)\">ops</span>", source: { label: "📄 Source", url: "https://www.asosplc.com/media/jpgfzvjz/interim-results-for-the-26-weeks-to-1-march-2026.pdf" } },
        { html: "<strong>Power Automate + Teams Premium</strong> <span style=\"color:var(--text-mid)\">ops</span>", source: { label: "📄 Source", url: "https://ukstories.microsoft.com/features/asos-and-microsoft-announce-new-three-year-ai-collaboration/" } },
        { html: "<strong>Demand forecasting ML</strong> <span style=\"color:var(--text-mid)\">supply_chain</span>", source: { label: "📄 Source", url: "https://ukstories.microsoft.com/features/asos-and-microsoft-announce-new-three-year-ai-collaboration/" } },
        { html: "<strong>Sierra AI customer service agents</strong> <span style=\"color:var(--text-mid)\">consumer</span>", source: { label: "📄 Source", url: "https://retailtechinnovationhub.com/home/2025/12/28/asos-reimagines-customer-experience-with-ai-as-online-fashion-retailer-inks-sierra-deal" } },
        ],
        sources: [
        { label: "📄 AI Stylist", url: "https://ukstories.microsoft.com/features/asos-and-microsoft-announce-new-three-year-ai-collaboration/" },
        { label: "📄 GitHub Copilot", url: "https://ukstories.microsoft.com/features/asos-and-microsoft-announce-new-three-year-ai-collaboration/" },
        { label: "📄 Microsoft 365 Copilot", url: "https://www.asosplc.com/media/jpgfzvjz/interim-results-for-the-26-weeks-to-1-march-2026.pdf" },
        { label: "📄 Power Automate + Teams Premium", url: "https://ukstories.microsoft.com/features/asos-and-microsoft-announce-new-three-year-ai-collaboration/" },
        { label: "📄 Demand forecasting ML", url: "https://ukstories.microsoft.com/features/asos-and-microsoft-announce-new-three-year-ai-collaboration/" },
        { label: "📄 Sierra AI customer service agents", url: "https://retailtechinnovationhub.com/home/2025/12/28/asos-reimagines-customer-experience-with-ai-as-online-fashion-retailer-inks-sierra-deal" },
        ],
      },
    },
    sources: [
      { label: "📄 AI Stylist", url: "https://ukstories.microsoft.com/features/asos-and-microsoft-announce-new-three-year-ai-collaboration/" },
      { label: "📄 Microsoft 365 Copilot", url: "https://www.asosplc.com/media/jpgfzvjz/interim-results-for-the-26-weeks-to-1-march-2026.pdf" },
      { label: "📄 Sierra AI customer service agents", url: "https://retailtechinnovationhub.com/home/2025/12/28/asos-reimagines-customer-experience-with-ai-as-online-fashion-retailer-inks-sierra-deal" },
    ],
  },
  "barilla": {
    production: {
      namedTools: {
        tools: [
        { html: "<strong>o9 Solutions</strong> <span style=\"color:var(--text-mid)\">supply_chain</span>", source: { label: "📄 Source", url: "https://o9solutions.com/news/o9-solutions-empowers-barilla-with-integrated-planning-capabilities/" } },
        { html: "<strong>Databricks Lakehouse</strong> <span style=\"color:var(--text-mid)\">analytics</span>", source: { label: "📄 Source", url: "https://www.databricks.com/customers/barilla" } },
        { html: "<strong>OMD AI marketing optimisation</strong> <span style=\"color:var(--text-mid)\">marketing</span>", source: { label: "📄 Source", url: "https://www.thedrum.com/awards-case-study/how-omd-revolutionized-barilla-s-marketing-with-ai" } },
        { html: "<strong>BITE Innovation Centre AI sensors</strong> <span style=\"color:var(--text-mid)\">ops</span>", source: { label: "📄 Source", url: "https://www.barillagroup.com/en/press-room/press-releases/barilla-bite-innovation-center/" } },
        ],
        sources: [
        { label: "📄 o9 Solutions", url: "https://o9solutions.com/news/o9-solutions-empowers-barilla-with-integrated-planning-capabilities/" },
        { label: "📄 Databricks Lakehouse", url: "https://www.databricks.com/customers/barilla" },
        { label: "📄 OMD AI marketing optimisation", url: "https://www.thedrum.com/awards-case-study/how-omd-revolutionized-barilla-s-marketing-with-ai" },
        { label: "📄 BITE Innovation Centre AI sensors", url: "https://www.barillagroup.com/en/press-room/press-releases/barilla-bite-innovation-center/" },
        ],
      },
    },
    sources: [
      { label: "📄 o9 Solutions", url: "https://o9solutions.com/news/o9-solutions-empowers-barilla-with-integrated-planning-capabilities/" },
      { label: "📄 Databricks Lakehouse", url: "https://www.databricks.com/customers/barilla" },
      { label: "📄 OMD AI marketing optimisation", url: "https://www.thedrum.com/awards-case-study/how-omd-revolutionized-barilla-s-marketing-with-ai" },
      { label: "📄 BITE Innovation Centre AI sensors", url: "https://www.barillagroup.com/en/press-room/press-releases/barilla-bite-innovation-center/" },
    ],
  },
  "beiersdorf": {
    leadership: {
      presenter: {
        html: "<strong>Pierre Kröning</strong> — Chief Information Officer + Managing Director Beiersdorf IT (effective 1 Sep 2025).",
        source: { label: "📄 Announcement", url: "https://www.beiersdorf.com/newsroom/press-information/all-press-releases/2025/09/03-pierre-kroening-appointed-as-beiersdorfs-new-cio" },
      },
    },
    production: {
      namedTools: {
        tools: [
        { html: "<strong>Uncountable AI</strong> <span style=\"color:var(--text-mid)\">ops</span>", source: { label: "📄 Source", url: "https://www.uncountable.com/resources/uncountable-beiersdorf" } },
        { html: "<strong>Insilico Medicine</strong> <span style=\"color:var(--text-mid)\">ops</span>", source: { label: "📄 Source", url: "https://www.eurekalert.org/news-releases/854293" } },
        { html: "<strong>Beiersdorf Connect</strong> <span style=\"color:var(--text-mid)\">ops</span>", source: { label: "📄 Source", url: "https://www.beiersdorf.com/research/our-way-of-working/beiersdorf-connect" } },
        { html: "<strong>Generative AI scaling programme (Google Cloud + Artefact)</strong> <span style=\"color:var(--text-mid)\">analytics</span>", source: { label: "📄 Source", url: "https://www.artefact.com/events/generative-ai-leveraging-todays-innovation-for-tomorrows-competitive-edge/" } },
        { html: "<strong>Internal ChatGPT deployment</strong> <span style=\"color:var(--text-mid)\">analytics</span>", source: { label: "📄 Source", url: "https://www.hamburg-business.com/en/news/beiersdorf-driving-ai-innovations" } },
        ],
        sources: [
        { label: "📄 Uncountable AI", url: "https://www.uncountable.com/resources/uncountable-beiersdorf" },
        { label: "📄 Insilico Medicine", url: "https://www.eurekalert.org/news-releases/854293" },
        { label: "📄 Beiersdorf Connect", url: "https://www.beiersdorf.com/research/our-way-of-working/beiersdorf-connect" },
        { label: "📄 Generative AI scaling programme (Google Cloud + Artefact)", url: "https://www.artefact.com/events/generative-ai-leveraging-todays-innovation-for-tomorrows-competitive-edge/" },
        { label: "📄 Internal ChatGPT deployment", url: "https://www.hamburg-business.com/en/news/beiersdorf-driving-ai-innovations" },
        ],
      },
    },
    sources: [
      { label: "📄 Uncountable AI", url: "https://www.uncountable.com/resources/uncountable-beiersdorf" },
      { label: "📄 Insilico Medicine", url: "https://www.eurekalert.org/news-releases/854293" },
      { label: "📄 Beiersdorf Connect", url: "https://www.beiersdorf.com/research/our-way-of-working/beiersdorf-connect" },
      { label: "📄 Generative AI scaling programme (Google Cloud + Artefact)", url: "https://www.artefact.com/events/generative-ai-leveraging-todays-innovation-for-tomorrows-competitive-edge/" },
      { label: "📄 Internal ChatGPT deployment", url: "https://www.hamburg-business.com/en/news/beiersdorf-driving-ai-innovations" },
      { label: "📄 Pierre Kröning — leadership announcement", url: "https://www.beiersdorf.com/newsroom/press-information/all-press-releases/2025/09/03-pierre-kroening-appointed-as-beiersdorfs-new-cio" },
    ],
  },
  "burberry": {
    leadership: {
      presenter: {
        html: "<strong>Charlotte Baldwin</strong> — Chief Information Officer (joined late March 2025).",
        source: { label: "📄 Announcement", url: "https://www.ciodive.com/news/Burberry-CIO-Charlotte-Baldwin/738940/" },
      },
    },
    production: {
      namedTools: {
        tools: [
        { html: "<strong>Penguin (internal LLM platform)</strong> <span style=\"color:var(--text-mid)\">consumer</span>", source: { label: "📄 Source", url: "https://www.dataiq.global/award-winner/most-innovative-use-of-ai-global-burberry/" } },
        { html: "<strong>Databricks + Snowplow</strong> <span style=\"color:var(--text-mid)\">analytics</span>", source: { label: "📄 Source", url: "https://www.databricks.com/customers/burberry-snowplow" } },
        { html: "<strong>Archive animation AI</strong> <span style=\"color:var(--text-mid)\">marketing</span>", source: { label: "📄 Source", url: "https://www.glossy.co/fashion/luxury/luxury-fashions-ai-marketing-experiments-hit-a-turning-point/" } },
        { html: "<strong>Burberry chatbot (Master of Code)</strong> <span style=\"color:var(--text-mid)\">consumer</span>", source: { label: "📄 Source", url: "https://masterofcode.com/portfolio/burberry-chatbot" } },
        { html: "<strong>Alloy Automation</strong> <span style=\"color:var(--text-mid)\">ops</span>", source: { label: "📄 Source", url: "https://www.runalloy.com/case-studies/burberry/" } },
        ],
        sources: [
        { label: "📄 Penguin (internal LLM platform)", url: "https://www.dataiq.global/award-winner/most-innovative-use-of-ai-global-burberry/" },
        { label: "📄 Databricks + Snowplow", url: "https://www.databricks.com/customers/burberry-snowplow" },
        { label: "📄 Archive animation AI", url: "https://www.glossy.co/fashion/luxury/luxury-fashions-ai-marketing-experiments-hit-a-turning-point/" },
        { label: "📄 Burberry chatbot (Master of Code)", url: "https://masterofcode.com/portfolio/burberry-chatbot" },
        { label: "📄 Alloy Automation", url: "https://www.runalloy.com/case-studies/burberry/" },
        ],
      },
    },
    sources: [
      { label: "📄 Penguin (internal LLM platform)", url: "https://www.dataiq.global/award-winner/most-innovative-use-of-ai-global-burberry/" },
      { label: "📄 Databricks + Snowplow", url: "https://www.databricks.com/customers/burberry-snowplow" },
      { label: "📄 Archive animation AI", url: "https://www.glossy.co/fashion/luxury/luxury-fashions-ai-marketing-experiments-hit-a-turning-point/" },
      { label: "📄 Burberry chatbot (Master of Code)", url: "https://masterofcode.com/portfolio/burberry-chatbot" },
      { label: "📄 Alloy Automation", url: "https://www.runalloy.com/case-studies/burberry/" },
      { label: "📄 Charlotte Baldwin — leadership announcement", url: "https://www.ciodive.com/news/Burberry-CIO-Charlotte-Baldwin/738940/" },
    ],
  },
  "carrefour": {
    leadership: {
      presenter: {
        html: "<strong>Sébastien Rozanes</strong> — Chief Data &amp; Analytics Officer.",
        source: { label: "📄 Announcement", url: "https://www.thoughtspot.com/data-chief/podcast" },
      },
    },
    production: {
      namedTools: {
        tools: [
        { html: "<strong>Hopla+</strong> <span style=\"color:var(--text-mid)\">consumer</span>", source: { label: "📄 Source", url: "https://www.carrefour.com/en/newsroom/hopla-generative-ai" } },
        { html: "<strong>Dynamic pricing engine</strong> <span style=\"color:var(--text-mid)\">merchandising</span>", source: { label: "📄 Source", url: "https://www.carrefour.com/en/newsroom" } },
        { html: "<strong>Product sheet enrichment (GenAI)</strong> <span style=\"color:var(--text-mid)\">merchandising</span>", source: { label: "📄 Source", url: "https://www.microsoft.com/en-us/industry/blog/retail/2024/04/02/threefold-revolution-the-influence-of-generative-ai-on-retail-and-consumer-goods/" } },
        ],
        sources: [
        { label: "📄 Hopla+", url: "https://www.carrefour.com/en/newsroom/hopla-generative-ai" },
        { label: "📄 Dynamic pricing engine", url: "https://www.carrefour.com/en/newsroom" },
        { label: "📄 Product sheet enrichment (GenAI)", url: "https://www.microsoft.com/en-us/industry/blog/retail/2024/04/02/threefold-revolution-the-influence-of-generative-ai-on-retail-and-consumer-goods/" },
        ],
      },
    },
    sources: [
      { label: "📄 Hopla+", url: "https://www.carrefour.com/en/newsroom/hopla-generative-ai" },
      { label: "📄 Dynamic pricing engine", url: "https://www.carrefour.com/en/newsroom" },
      { label: "📄 Product sheet enrichment (GenAI)", url: "https://www.microsoft.com/en-us/industry/blog/retail/2024/04/02/threefold-revolution-the-influence-of-generative-ai-on-retail-and-consumer-goods/" },
      { label: "📄 Sébastien Rozanes — leadership announcement", url: "https://www.thoughtspot.com/data-chief/podcast" },
    ],
  },
  "decathlon": {
    leadership: {
      presenter: {
        html: "<strong>Didier Mamma</strong> — Chief Data &amp; AI Officer.",
        source: { label: "📄 Announcement", url: "https://www.republik-it.fr/decideurs-it/gouvernance/didier-mamma-promu-chief-data-ai-officer-de-decathlon.html" },
      },
    },
    production: {
      namedTools: {
        tools: [
        { html: "<strong>AI Factory (internal industrial-AI platform)</strong> <span style=\"color:var(--text-mid)\">ops</span>", source: { label: "📄 Source", url: "https://www.horrea.fr/en/resources/decathlon-ai-factory-data-into-performance/" } },
        { html: "<strong>Conseilsport AI assistant</strong> <span style=\"color:var(--text-mid)\">consumer</span>", source: { label: "📄 Source", url: "https://conseilsport.decathlon.fr/sport-et-intelligence-artificielle-comment-lia-bouge-les-lignes" } },
        ],
        sources: [
        { label: "📄 AI Factory (internal industrial-AI platform)", url: "https://www.horrea.fr/en/resources/decathlon-ai-factory-data-into-performance/" },
        { label: "📄 Conseilsport AI assistant", url: "https://conseilsport.decathlon.fr/sport-et-intelligence-artificielle-comment-lia-bouge-les-lignes" },
        ],
      },
    },
    sources: [
      { label: "📄 AI Factory (internal industrial-AI platform)", url: "https://www.horrea.fr/en/resources/decathlon-ai-factory-data-into-performance/" },
      { label: "📄 Conseilsport AI assistant", url: "https://conseilsport.decathlon.fr/sport-et-intelligence-artificielle-comment-lia-bouge-les-lignes" },
      { label: "📄 Didier Mamma — leadership announcement", url: "https://www.republik-it.fr/decideurs-it/gouvernance/didier-mamma-promu-chief-data-ai-officer-de-decathlon.html" },
    ],
  },
  "heineken": {
    leadership: {
      presenter: {
        html: "<strong>Romain Apert</strong> — Chief Digital &amp; Technology Officer.",
        source: { label: "📄 Announcement", url: "https://www.theheinekencompany.com/newsroom/heineken-appoints-new-chief-digital--technology-officer/" },
      },
    },
    sources: [
      { label: "📄 Romain Apert — leadership announcement", url: "https://www.theheinekencompany.com/newsroom/heineken-appoints-new-chief-digital--technology-officer/" },
    ],
  },
  "hm": {
    leadership: {
      presenter: {
        html: "<strong>Daniel Erver</strong> — CEO.",
        source: { label: "📄 Announcement", url: "https://hmgroup.com/investors/" },
      },
    },
    production: {
      namedTools: {
        tools: [
        { html: "<strong>AI design assistant (in-house)</strong> <span style=\"color:var(--text-mid)\">creative</span>", source: { label: "📄 Source", url: "https://hmgroup.com" } },
        { html: "<strong>Allocation &amp; demand ML</strong> <span style=\"color:var(--text-mid)\">supply_chain</span>", source: { label: "📄 Source", url: "https://hmgroup.com" } },
        ],
        sources: [
        { label: "📄 AI design assistant (in-house)", url: "https://hmgroup.com" },
        { label: "📄 Allocation & demand ML", url: "https://hmgroup.com" },
        ],
      },
    },
    sources: [
      { label: "📄 AI design assistant (in-house)", url: "https://hmgroup.com" },
      { label: "📄 Daniel Erver — leadership announcement", url: "https://hmgroup.com/investors/" },
    ],
  },
  "inditex": {
    production: {
      namedTools: {
        tools: [
        { html: "<strong>Inventory &amp; demand AI (in-house)</strong> <span style=\"color:var(--text-mid)\">supply_chain</span>", source: { label: "📄 Source", url: "https://www.inditex.com" } },
        { html: "<strong>RFID + ML store ops</strong> <span style=\"color:var(--text-mid)\">ops</span>", source: { label: "📄 Source", url: "https://www.inditex.com" } },
        ],
        sources: [
        { label: "📄 Inventory & demand AI (in-house)", url: "https://www.inditex.com" },
        { label: "📄 RFID + ML store ops", url: "https://www.inditex.com" },
        ],
      },
    },
    sources: [
      { label: "📄 Inventory & demand AI (in-house)", url: "https://www.inditex.com" },
    ],
  },
  "kering": {
    leadership: {
      presenter: {
        html: "<strong>Pierre Houlès</strong> — Chief Digital, AI &amp; IT Officer (ExCom).",
        source: { label: "📄 Announcement", url: "https://www.globenewswire.com/news-release/2026/03/17/3257505/0/en/Pierre-Houl%C3%A8s-appointed-Chief-Digital-AI-IT-Officer-at-Kering.html" },
      },
    },
    sources: [
      { label: "📄 Pierre Houlès — leadership announcement", url: "https://www.globenewswire.com/news-release/2026/03/17/3257505/0/en/Pierre-Houl%C3%A8s-appointed-Chief-Digital-AI-IT-Officer-at-Kering.html" },
    ],
  },
  "loreal": {
    leadership: {
      presenter: {
        html: "<strong>Samuel du Retail</strong> — General Manager AI – Data – Shared Services.",
        source: { label: "📄 Announcement", url: "https://www.loreal-finance.com/eng/press-release/annual-general-meeting-24-april-2026" },
      },
    },
    production: {
      namedTools: {
        tools: [
        { html: "<strong>Beauty Genius (GenAI advisor)</strong> <span style=\"color:var(--text-mid)\">consumer</span>", source: { label: "📄 Source", url: "https://www.loreal.com/en/news/beauty-tech/beauty-genius/" } },
        { html: "<strong>ModiFace AR try-on</strong> <span style=\"color:var(--text-mid)\">consumer</span>", source: { label: "📄 Source", url: "https://www.loreal.com/en/news/beauty-tech/modiface/" } },
        { html: "<strong>CreAItech (creative GenAI)</strong> <span style=\"color:var(--text-mid)\">marketing</span>", source: { label: "📄 Source", url: "https://www.loreal.com/en/news/" } },
        { html: "<strong>Claude for coding, analytics &amp; SQL (Anthropic, employee-facing)</strong> <span style=\"color:var(--text-mid)\">ops</span>", source: { label: "📄 Source", url: "https://resources.anthropic.com/hubfs/The-Enterprise-AI-Transformation-Guide-for-Retail.pdf?hsLang=en" } },
        ],
        sources: [
        { label: "📄 Beauty Genius (GenAI advisor)", url: "https://www.loreal.com/en/news/beauty-tech/beauty-genius/" },
        { label: "📄 ModiFace AR try-on", url: "https://www.loreal.com/en/news/beauty-tech/modiface/" },
        { label: "📄 CreAItech (creative GenAI)", url: "https://www.loreal.com/en/news/" },
        { label: "📄 Claude for coding, analytics & SQL (Anthropic, employee-facing)", url: "https://resources.anthropic.com/hubfs/The-Enterprise-AI-Transformation-Guide-for-Retail.pdf?hsLang=en" },
        ],
      },
    },
    sources: [
      { label: "📄 Beauty Genius (GenAI advisor)", url: "https://www.loreal.com/en/news/beauty-tech/beauty-genius/" },
      { label: "📄 ModiFace AR try-on", url: "https://www.loreal.com/en/news/beauty-tech/modiface/" },
      { label: "📄 CreAItech (creative GenAI)", url: "https://www.loreal.com/en/news/" },
      { label: "📄 Claude for coding, analytics & SQL (Anthropic, employee-facing)", url: "https://resources.anthropic.com/hubfs/The-Enterprise-AI-Transformation-Guide-for-Retail.pdf?hsLang=en" },
      { label: "📄 Samuel du Retail — leadership announcement", url: "https://www.loreal-finance.com/eng/press-release/annual-general-meeting-24-april-2026" },
    ],
  },
  "lvmh": {
    leadership: {
      presenter: {
        html: "<strong>Stéphane Bianchi</strong> — Group Managing Director.",
        source: { label: "📄 Announcement", url: "https://www.lvmh.com/en/investors" },
      },
    },
    production: {
      namedTools: {
        tools: [
        { html: "<strong>Sephora AI Beauty Advisor</strong> <span style=\"color:var(--text-mid)\">consumer</span>", source: { label: "📄 Source", url: "https://www.sephora.com" } },
        { html: "<strong>DIOR ID virtual try-on</strong> <span style=\"color:var(--text-mid)\">consumer</span>", source: { label: "📄 Source", url: "https://www.dior.com" } },
        ],
        sources: [
        { label: "📄 Sephora AI Beauty Advisor", url: "https://www.sephora.com" },
        { label: "📄 DIOR ID virtual try-on", url: "https://www.dior.com" },
        ],
      },
    },
    sources: [
      { label: "📄 Sephora AI Beauty Advisor", url: "https://www.sephora.com" },
      { label: "📄 DIOR ID virtual try-on", url: "https://www.dior.com" },
      { label: "📄 Stéphane Bianchi — leadership announcement", url: "https://www.lvmh.com/en/investors" },
    ],
  },
  "marks-spencer": {
    leadership: {
      presenter: {
        html: "<strong>Stuart Machin</strong>.",
        
      },
    },
    production: {
      namedTools: {
        tools: [
        { html: "<strong>Sparks wallet personalisation engine</strong> <span style=\"color:var(--text-mid)\">consumer</span>", source: { label: "📄 Source", url: "https://corporate.marksandspencer.com/sites/marksandspencer/files/2026-05/fy26-rns.pdf" } },
        ],
        sources: [
        { label: "📄 Sparks wallet personalisation engine", url: "https://corporate.marksandspencer.com/sites/marksandspencer/files/2026-05/fy26-rns.pdf" },
        ],
      },
    },
    sources: [
      { label: "📄 Sparks wallet personalisation engine", url: "https://corporate.marksandspencer.com/sites/marksandspencer/files/2026-05/fy26-rns.pdf" },
    ],
  },
  "nestle": {
    leadership: {
      presenter: {
        html: "<strong>Laurent Freixe</strong> — CEO.",
        source: { label: "📄 Announcement", url: "https://www.nestle.com/investors" },
      },
    },
    production: {
      namedTools: {
        tools: [
        { html: "<strong>AI marketing content generation</strong> <span style=\"color:var(--text-mid)\">marketing</span>", source: { label: "📄 Source", url: "https://www.nestle.com" } },
        { html: "<strong>Cocoa Compass (supply chain)</strong> <span style=\"color:var(--text-mid)\">supply_chain</span>", source: { label: "📄 Source", url: "https://www.nestle.com" } },
        ],
        sources: [
        { label: "📄 AI marketing content generation", url: "https://www.nestle.com" },
        { label: "📄 Cocoa Compass (supply chain)", url: "https://www.nestle.com" },
        ],
      },
    },
    sources: [
      { label: "📄 AI marketing content generation", url: "https://www.nestle.com" },
      { label: "📄 Laurent Freixe — leadership announcement", url: "https://www.nestle.com/investors" },
    ],
  },
  "ocado": {
    leadership: {
      presenter: {
        html: "<strong>James Matthews</strong> — CEO Ocado Technology.",
        source: { label: "📄 Announcement", url: "https://www.ocadogroup.com/investors/" },
      },
    },
    production: {
      namedTools: {
        tools: [
        { html: "<strong>Ocado Smart Platform (OSP) ML</strong> <span style=\"color:var(--text-mid)\">ops</span>", source: { label: "📄 Source", url: "https://www.ocadogroup.com/technology/" } },
        { html: "<strong>On-Grid Robotic Pick</strong> <span style=\"color:var(--text-mid)\">ops</span>", source: { label: "📄 Source", url: "https://www.ocadogroup.com/technology/" } },
        { html: "<strong>Re:Imagined automation suite</strong> <span style=\"color:var(--text-mid)\">ops</span>", source: { label: "📄 Source", url: "https://www.ocadogroup.com" } },
        ],
        sources: [
        { label: "📄 Ocado Smart Platform (OSP) ML", url: "https://www.ocadogroup.com/technology/" },
        { label: "📄 On-Grid Robotic Pick", url: "https://www.ocadogroup.com/technology/" },
        { label: "📄 Re:Imagined automation suite", url: "https://www.ocadogroup.com" },
        ],
      },
    },
    sources: [
      { label: "📄 Ocado Smart Platform (OSP) ML", url: "https://www.ocadogroup.com/technology/" },
      { label: "📄 Re:Imagined automation suite", url: "https://www.ocadogroup.com" },
      { label: "📄 James Matthews — leadership announcement", url: "https://www.ocadogroup.com/investors/" },
    ],
  },
  "on-running": {
    leadership: {
      presenter: {
        html: "<strong>Thomas Williams</strong> — Senior Director of AI Labs.",
        source: { label: "📄 Announcement", url: "https://www.linkedin.com/in/itwilliams/" },
      },
    },
    production: {
      namedTools: {
        tools: [
        { html: "<strong>Design AI integration</strong> <span style=\"color:var(--text-mid)\">creative</span>" },
        { html: "<strong>Innovation workflow AI</strong> <span style=\"color:var(--text-mid)\">ops</span>" },
        ],
        sources: [

        ],
      },
    },
    sources: [
      { label: "📄 Thomas Williams — leadership announcement", url: "https://www.linkedin.com/in/itwilliams/" },
    ],
  },
  "tesco": {
    production: {
      namedTools: {
        tools: [
        { html: "<strong>Clubcard personalisation (ML)</strong> <span style=\"color:var(--text-mid)\">consumer</span>", source: { label: "📄 Source", url: "https://www.tescoplc.com" } },
        { html: "<strong>AI demand forecasting</strong> <span style=\"color:var(--text-mid)\">supply_chain</span>", source: { label: "📄 Source", url: "https://www.tescoplc.com" } },
        ],
        sources: [
        { label: "📄 Clubcard personalisation (ML)", url: "https://www.tescoplc.com" },
        { label: "📄 AI demand forecasting", url: "https://www.tescoplc.com" },
        ],
      },
    },
    sources: [
      { label: "📄 Clubcard personalisation (ML)", url: "https://www.tescoplc.com" },
    ],
  },
  "unilever": {
    leadership: {
      presenter: {
        html: "<strong>Hein Schumacher</strong> — CEO.",
        source: { label: "📄 Announcement", url: "https://www.unilever.com/investors/" },
      },
    },
    production: {
      namedTools: {
        tools: [
        { html: "<strong>AI marketing creative generation</strong> <span style=\"color:var(--text-mid)\">marketing</span>", source: { label: "📄 Source", url: "https://www.unilever.com" } },
        { html: "<strong>Brand DNAi (proprietary AI governance platform)</strong> <span style=\"color:var(--text-mid)\">marketing</span>", source: { label: "📄 Source", url: "https://www.unilever.com/news/news-search/2026/how-ai-is-transforming-innovation-in-unilever-beauty-wellbeing/" } },
        { html: "<strong>Beauty &amp; Wellbeing virtual cohorts (microbiome-seeded GenAI)</strong> <span style=\"color:var(--text-mid)\">ops</span>", source: { label: "📄 Source", url: "https://www.unilever.com/news/news-search/2026/how-ai-is-transforming-innovation-in-unilever-beauty-wellbeing/" } },
        ],
        sources: [
        { label: "📄 AI marketing creative generation", url: "https://www.unilever.com" },
        { label: "📄 Brand DNAi (proprietary AI governance platform)", url: "https://www.unilever.com/news/news-search/2026/how-ai-is-transforming-innovation-in-unilever-beauty-wellbeing/" },
        { label: "📄 Beauty & Wellbeing virtual cohorts (microbiome-seeded GenAI)", url: "https://www.unilever.com/news/news-search/2026/how-ai-is-transforming-innovation-in-unilever-beauty-wellbeing/" },
        ],
      },
    },
    sources: [
      { label: "📄 AI marketing creative generation", url: "https://www.unilever.com" },
      { label: "📄 Brand DNAi (proprietary AI governance platform)", url: "https://www.unilever.com/news/news-search/2026/how-ai-is-transforming-innovation-in-unilever-beauty-wellbeing/" },
      { label: "📄 Hein Schumacher — leadership announcement", url: "https://www.unilever.com/investors/" },
    ],
  },
  "zalando": {
    leadership: {
      presenter: {
        html: "<strong>David Schröder</strong> — Co-CEO.",
        source: { label: "📄 Announcement", url: "https://corporate.zalando.com/en/investor-relations" },
      },
    },
    production: {
      namedTools: {
        tools: [
        { html: "<strong>Zalando Assistant (GenAI)</strong> <span style=\"color:var(--text-mid)\">consumer</span>", source: { label: "📄 Source", url: "https://corporate.zalando.com/en/newsroom" } },
        { html: "<strong>Size &amp; Fit recommendations (ML)</strong> <span style=\"color:var(--text-mid)\">consumer</span>", source: { label: "📄 Source", url: "https://corporate.zalando.com/" } },
        ],
        sources: [
        { label: "📄 Zalando Assistant (GenAI)", url: "https://corporate.zalando.com/en/newsroom" },
        { label: "📄 Size & Fit recommendations (ML)", url: "https://corporate.zalando.com/" },
        ],
      },
    },
    sources: [
      { label: "📄 Zalando Assistant (GenAI)", url: "https://corporate.zalando.com/en/newsroom" },
      { label: "📄 Size & Fit recommendations (ML)", url: "https://corporate.zalando.com/" },
      { label: "📄 David Schröder — leadership announcement", url: "https://corporate.zalando.com/en/investor-relations" },
    ],
  },
};
