/**
 * scripts/sync-calendar.ts
 *
 * Single sync command for the earnings calendar.
 * Reads the trading calendar table from your notes vault § 3
 * (`07_shared_sources.md`) and:
 *   1. Pushes to Redis as `rachel:calendar` (consumed by /api/earnings-calendar,
 *      /api/dashboard, and the landing page widget).
 *   2. Regenerates `data/earnings-calendar.json` (consumed by /app/today and
 *      any other app pages that need static fallback data).
 *
 * The ONLY file you ever edit for earnings dates is 07_shared_sources.md § 3.
 * Running this script propagates those edits everywhere.
 *
 * Usage:
 *   node_modules/.bin/tsx --env-file=.env.local scripts/sync-calendar.ts
 *   node_modules/.bin/tsx --env-file=.env.local scripts/sync-calendar.ts --dry-run
 *
 * Environment required:
 *   UPSTASH_URL + UPSTASH_TOKEN  (for Redis push)
 *   SHARED_SOURCES_PATH          (absolute path to 07_shared_sources.md)
 */

import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { redis } from "@/lib/redis";

const SOURCE_PATH = process.env.SHARED_SOURCES_PATH ?? "";
const REDIS_KEY = "rachel:calendar";

interface CalendarEntry {
  slug: string;
  company: string;
  sector: string;
  last_earnings: string;
  next_earnings: string; // may include " tbc" suffix
  next_earnings_date: string; // ISO date only, no suffix
  is_tbc: boolean;
  ir_url: string | null;
}

function parseTable(md: string): CalendarEntry[] {
  // Find § 3 section
  const sectionStart = md.indexOf("## 3. Trading and Earnings Calendars");
  if (sectionStart === -1) throw new Error("§ 3 section not found");
  const sectionEnd = md.indexOf("\n## ", sectionStart + 1);
  const section =
    sectionEnd === -1 ? md.slice(sectionStart) : md.slice(sectionStart, sectionEnd);

  // Match the data table (header + separator + rows)
  const lines = section
    .split("\n")
    .filter((l) => l.startsWith("|") && !l.startsWith("|---"));
  if (lines.length < 2) throw new Error("calendar table not found in § 3");

  // Drop header line
  const dataLines = lines.slice(1);

  const entries: CalendarEntry[] = [];
  for (const line of dataLines) {
    const cells = line
      .split("|")
      .map((c) => c.trim())
      .filter((_, i, a) => i > 0 && i < a.length - 1); // drop leading/trailing empty
    if (cells.length !== 6) {
      console.warn(`skipping malformed row: ${line}`);
      continue;
    }
    const [slug, company, sector, last_earnings, next_earnings, ir_raw] = cells;
    if (slug === "slug") continue; // header repeat
    const is_tbc = next_earnings.includes("tbc");
    const next_earnings_date = next_earnings.replace(/\s*tbc\s*$/i, "").trim();
    if (!/^\d{4}-\d{2}-\d{2}$/.test(next_earnings_date)) {
      console.warn(
        `skipping ${slug}: next_earnings not ISO date (got "${next_earnings}")`,
      );
      continue;
    }
    const ir_url =
      ir_raw && !ir_raw.startsWith("_") && ir_raw !== "(tbc)" ? ir_raw : null;
    entries.push({
      slug,
      company,
      sector,
      last_earnings,
      next_earnings,
      next_earnings_date,
      is_tbc,
      ir_url,
    });
  }

  // Sort ASC by next_earnings_date
  entries.sort((a, b) =>
    a.next_earnings_date.localeCompare(b.next_earnings_date),
  );
  return entries;
}

async function main() {
  const dryRun = process.argv.includes("--dry-run");

  const md = await readFile(SOURCE_PATH, "utf-8");
  const entries = parseTable(md);

  console.log(`Parsed ${entries.length} entries from § 3`);
  console.log(
    `First 5 by next_earnings: ${entries
      .slice(0, 5)
      .map((e) => `${e.company} (${e.next_earnings})`)
      .join(", ")}`,
  );

  const payload = {
    generatedAt: new Date().toISOString(),
    source: "07_shared_sources.md § 3",
    count: entries.length,
    entries,
  };

  // Generate the JSON artifact consumed by /app/today (fallback when Redis unavailable)
  const jsonArtifact = {
    _note: "AUTO-GENERATED by scripts/sync-calendar.ts from 07_shared_sources.md §3. DO NOT EDIT MANUALLY — changes will be overwritten on next sync.",
    _source: "07_shared_sources.md § 3 (your notes vault)",
    generatedAt: new Date().toISOString(),
    entries: entries.map((e) => ({
      slug: e.slug,
      company: e.company,
      sector: e.sector,
      last_earnings: e.last_earnings,
      next_earnings_date: e.next_earnings_date,
      is_tbc: e.is_tbc,
      ir_url: e.ir_url,
    })),
  };

  if (dryRun) {
    console.log("\n--dry-run: not pushing to Redis or writing JSON");
    console.log(JSON.stringify(payload, null, 2).slice(0, 2000));
    return;
  }

  await redis.set(REDIS_KEY, payload);
  console.log(`✓ Pushed to Redis → ${REDIS_KEY} (${entries.length} entries)`);

  const jsonPath = join(process.cwd(), "data", "earnings-calendar.json");
  await writeFile(jsonPath, JSON.stringify(jsonArtifact, null, 2) + "\n", "utf-8");
  console.log(`✓ Wrote ${jsonPath} (${entries.length} entries)`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
