/**
 * sync-template-overlays — keep the Vercel profile page in sync with MD edits.
 *
 * Reads every `data/companies/*.md`, builds a partial template overlay per
 * profile from fields that are now driven from the MD (recentSources,
 * cSuiteAIPresenter, namedProductionTools), and writes the merged result to
 * `lib/profiles/template/data/auto-md-sync.generated.ts`.
 *
 * That file is imported last in `lib/profiles/template/data/index.ts`, so any
 * new sources / tools / leadership change you add to the MD shows up on
 * /app/companies/<slug> on the next deploy without hand-editing enriched.ts.
 *
 * Invoked automatically at the end of `scripts/seed-profiles.ts`.
 */

import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { parseAllProfiles } from "../lib/profiles/parse";
import type { CompanyProfile } from "../lib/profiles/schema";

const HEADER = `// AUTO-GENERATED by scripts/sync-template-overlays.ts — DO NOT EDIT BY HAND.
// Source of truth: data/companies/*.md
//
// Re-runs at the end of every \`tsx scripts/seed-profiles.ts\` invocation.
// Wired into lib/profiles/template/data/index.ts as the last overlay layer
// so anything added to a profile MD shows up on /app/companies/<slug>.

import type { CompanyTemplateData } from "../schema";

`;

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function formatDate(iso: string | undefined): string {
  if (!iso) return "";
  const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(iso);
  if (!m) return iso;
  const months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
  return `${parseInt(m[3], 10)} ${months[parseInt(m[2], 10) - 1]} ${m[1]}`;
}

function sanitiseLabel(s: string): string {
  return s.replace(/`/g, "'").replace(/\$\{/g, "$ {");
}

function overlayForProfile(p: CompanyProfile): string {
  const slug = p.slug;
  const sourcesEntries: Array<{ label: string; url: string }> = [];

  // recentSources — explicit news/case-study list, prepended (newest curated wins)
  for (const r of p.recentSources ?? []) {
    const dateLabel = r.date ? ` (${formatDate(r.date)})` : "";
    sourcesEntries.push({
      label: `📄 ${sanitiseLabel(r.label)}${dateLabel}`,
      url: r.url,
    });
  }

  // namedProductionTools — surface their sourceUrls in the page sources strip
  for (const t of p.aiPerception?.namedProductionTools ?? []) {
    if (!t.sourceUrl || t.sourceUrl === "?" || sourcesEntries.some((s) => s.url === t.sourceUrl)) continue;
    sourcesEntries.push({
      label: `📄 ${sanitiseLabel(t.name)}`,
      url: t.sourceUrl,
    });
  }

  // cSuiteAIPresenter sourceUrl
  const presenter = p.aiPerception?.cSuiteAIPresenter;
  let presenterBlock = "";
  if (presenter?.exists && presenter.name) {
    if (presenter.sourceUrl && !sourcesEntries.some((s) => s.url === presenter.sourceUrl)) {
      sourcesEntries.push({
        label: `📄 ${sanitiseLabel(presenter.name)} — leadership announcement`,
        url: presenter.sourceUrl,
      });
    }
    presenterBlock = `
    leadership: {
      presenter: {
        html: ${JSON.stringify(`<strong>${escapeHtml(presenter.name)}</strong>${presenter.role ? ` — ${escapeHtml(presenter.role)}` : ""}.`)},
        ${presenter.sourceUrl ? `source: { label: "📄 Announcement", url: ${JSON.stringify(presenter.sourceUrl)} },` : ""}
      },
    },`;
  }

  // namedTools block — only emit if we have any
  const tools = (p.aiPerception?.namedProductionTools ?? []).filter((t) => t.name);
  let productionBlock = "";
  if (tools.length > 0) {
    const toolLines = tools
      .map((t) => {
        const cat = t.category ? ` <span style="color:var(--text-mid)">${escapeHtml(t.category)}</span>` : "";
        const html = `<strong>${escapeHtml(t.name)}</strong>${cat}`;
        const src = t.sourceUrl ? `, source: { label: "📄 Source", url: ${JSON.stringify(t.sourceUrl)} }` : "";
        return `        { html: ${JSON.stringify(html)}${src} },`;
      })
      .join("\n");
    const toolSources = tools
      .filter((t) => t.sourceUrl)
      .map((t) => `        { label: ${JSON.stringify(`📄 ${sanitiseLabel(t.name)}`)}, url: ${JSON.stringify(t.sourceUrl)} },`)
      .join("\n");
    productionBlock = `
    production: {
      namedTools: {
        tools: [
${toolLines}
        ],
        sources: [
${toolSources}
        ],
      },
    },`;
  }

  // dedupe sources by URL, cap at 12
  const seen = new Set<string>();
  const dedupedSources = sourcesEntries.filter((s) => {
    if (seen.has(s.url)) return false;
    seen.add(s.url);
    return true;
  }).slice(0, 12);

  const sourcesBlock = dedupedSources.length
    ? `
    sources: [
${dedupedSources.map((s) => `      { label: ${JSON.stringify(s.label)}, url: ${JSON.stringify(s.url)} },`).join("\n")}
    ],`
    : "";

  // furtherReading: just the recentSources, since those are explicit news
  const further = (p.recentSources ?? []).map((r) => ({
    label: `${r.label}${r.date ? ` (${formatDate(r.date)})` : ""}`,
    url: r.url,
  }));
  const furtherBlock = further.length
    ? `
    furtherReading: [
${further.map((s) => `      { label: ${JSON.stringify(s.label)}, url: ${JSON.stringify(s.url)} },`).join("\n")}
    ],`
    : "";

  if (!presenterBlock && !productionBlock && !sourcesBlock && !furtherBlock) return "";

  return `  ${JSON.stringify(slug)}: {${presenterBlock}${productionBlock}${sourcesBlock}${furtherBlock}
  },\n`;
}

async function main() {
  const companiesDir = resolve(process.cwd(), "data/companies");
  const profiles = await parseAllProfiles(companiesDir);
  const ok = profiles.filter((p) => p.ok && p.profile).map((p) => p.profile!);

  const body = ok.map(overlayForProfile).join("");

  const out = `${HEADER}export const autoMdSync: Record<string, Partial<CompanyTemplateData>> = {
${body}};
`;

  const outPath = resolve(process.cwd(), "lib/profiles/template/data/auto-md-sync.generated.ts");
  await writeFile(outPath, out, "utf8");
  console.log(`✓ Wrote ${outPath} (${ok.length} profiles, ${body.split("\n").length - 1} lines)`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
